# Generated by Django 5.1.3 on 2025-01-28 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='added',
        ),
    ]
