# Generated by Django 5.1.3 on 2025-01-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_remove_song_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(default='kipelov', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
