# Generated by Django 5.1.3 on 2025-01-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_author_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(default='pyt-naverh', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default='rock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='slug',
            field=models.SlugField(default='ya-svoboden', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='album',
            constraint=models.UniqueConstraint(fields=('slug', 'author'), name='unique_album_slug_per_author'),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.UniqueConstraint(fields=('slug', 'author'), name='unique_song_slug_per_author'),
        ),
    ]
