# Generated by Django 5.1.3 on 2025-01-29 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_alter_genre_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 1, 29, 0, 0)),
            preserve_default=False,
        ),
    ]
