# Generated by Django 5.1.5 on 2025-02-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0009_album_cover_author_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='songs/'),
        ),
    ]
