# Generated by Django 5.1.5 on 2025-02-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0010_song_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'альбом', 'verbose_name_plural': 'альбомы'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'автора', 'verbose_name_plural': 'авторы'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'жанр', 'verbose_name_plural': 'жанры'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'verbose_name': 'песню', 'verbose_name_plural': 'песни'},
        ),
        migrations.AlterField(
            model_name='song',
            name='added',
            field=models.DateTimeField(),
        ),
    ]
