# Generated by Django 5.1.5 on 2025-02-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0011_alter_album_options_alter_author_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
